# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learned optimism
email: gregg@codepinata.com
description: > # this means to ignore newlines until "baseurl:"
  explorations in better communication, health and optimism
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://optimist.meluski.com"
twitter_username: gmeluski
github_username: gmeluski

# Build settings
markdown: kramdown
